language: cpp
env:
  global:
    - DEPS=""
matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode9.4
      env:
        - DEPS="${DEPS} readline llvm@6"
        - LLVM_DIR=/usr/local/opt/llvm@6/lib/cmake/llvm/
        - ARGS=-V
    - os: linux
      compiler: g++
      root: required
      dist: trusty
      group: deprecated-2017Q4
      services:
        - docker
      env:
        - DIST=xenial
        - DEPS="llvm-3.7-dev cmake libedit-dev g++ libncurses5-dev zlib1g-dev libreadline-dev python2.7"
        - ARGS=-V
    - os: linux
      compiler: g++
      root: required
      dist: trusty
      group: deprecated-2017Q4
      services:
        - docker
      env:
        - DIST=xenial
        - DEPS="llvm-4.0-dev cmake libedit-dev g++ libncurses5-dev zlib1g-dev libreadline-dev python2.7"
        - ARGS=-V
    - os: linux
      compiler: g++
      root: required
      dist: trusty
      group: deprecated-2017Q4
      services:
        - docker
      env:
        - DIST=xenial
        - DEPS="llvm-6.0-dev cmake libedit-dev g++ libncurses5-dev zlib1g-dev libreadline-dev python2.7"
        - ARGS=-V
    - os: linux
      compiler: g++
      language: nix
      nix: 2.0.4
      group: deprecated-2017Q4
      script: nix-build

install:
  - if [ $TRAVIS_OS_NAME = osx   ]; then brew update && brew install -v ${DEPS} && find /usr/local/opt/llvm@6/ | grep cmake; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then cd docker/build && docker build . -f ./${DIST}.Dockerfile -t hobbes:build --build-arg DEPS; cd -; fi

script:
  - if [ $TRAVIS_OS_NAME = osx   ]; then mkdir build && cd build/ && cmake .. && make && make test; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then docker run -it -v ${PWD}:/src hobbes:build; fi

branches:
  only:
    - master
    - travis
